[workspace]
members = ["auth", "config", "ctl", "mock", "tun"]
resolver = "2"

[workspace.package]
version = "0.1.2"

[patch.crates-io]
libwebrtc = { path = "livekit/libwebrtc" }
livekit-protocol = { path = "livekit/livekit-protocol" }
livekit-runtime = { path = "livekit/livekit-runtime" }
webrtc-sys = { path = "livekit/webrtc-sys" }
webrtc-sys-build = { path = "livekit/webrtc-sys/build" }

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"
