#!/bin/sh
# Generates VP9 black keyframes for each WebRTC adaptation resolution and
# emits them as Rust source.  Run as:
#
#   ./gen-ivf.sh > tun/src/protozoa/vp9.rs
#
# Requires: ffmpeg with libvpx-vp9, xxd
set -eu

# IVF layout: 32-byte file header + 12-byte per-frame header = 44 bytes before
# the VP9 bitstream.  tail -c +N is 1-indexed, so +45 skips exactly 44 bytes.
IVF_SKIP=45

SIZES="1280x720 960x540 640x360 480x270 320x180 240x135"

cat <<'EOF'
// Auto-generated by gen-ivf.sh — do not edit manually.
// Regenerate with: ./gen-ivf.sh > tun/src/protozoa/vp9.rs
//
// One minimal black VP9 keyframe per resolution in libwebrtc's VideoAdapter
// down-step sequence from 1280x720.  Used by hook_before_vp9_reference_find
// to seed the decoder when the sender's encoder is at a given resolution.

#![cfg_attr(rustfmt, rustfmt_skip)]

pub struct PrebuiltKeyframe<'a> {
    pub width: u16,
    pub height: u16,
    pub data: &'a [u8],
}

EOF

printf "pub const VP9_BLACK_KEYFRAMES: &[PrebuiltKeyframe] = &[\n"

for size in $SIZES; do
    name=$(echo "$size" | tr 'x' 'X')
    w=$(echo "$size" | cut -dx -f1)
    h=$(echo "$size" | cut -dx -f2)
    printf "    PrebuiltKeyframe {\n"
    printf "        width: %s,\n" "$w"
    printf "        height: %s,\n" "$h"
    printf "        data: &[\n"
    ffmpeg -hide_banner -loglevel error \
           -f lavfi -i color=c=black:size="$size":rate=1 \
           -vcodec libvpx-vp9 -frames:v 1 -f ivf pipe:1 \
        | tail -c +"$IVF_SKIP" \
        | xxd -i -c 14 \
        | sed 's/^[[:space:]]*/            /'
    printf "        ],\n"
    printf "    },\n"

done

printf "];\n"
